### ISSUE TITLE
Display more than one snapshot in QuickLook

### ISSUE THREAD

**Issue by Diskutant** [Marginal/QLVideo#34] opened 2016-06-23 07:08 UTC
Is it possible to display like 4 snapshots instead of one? Each snapshot could have a resolution like 960x540 (that's (1920/2)x(1080/2)) each snapshot from a different part of the movie like 10 seconds in, 2/4 in, 3/4 in and like 1 minute before end. This behavior would be good for movies longer than 15 minutes or something around that. And old behavior for shorter movies.

What do you think?

**Comment by Marginal** [comment] 2016-06-23 10:51
Duplicate of #23

**Closed by Marginal** 2016-06-23 10:51 UTC
Labels: duplicate
