### ISSUE TITLE
How to debug non-showing thumbnails?

### ISSUE THREAD

**Issue by ear** [Marginal/QLVideo#26] opened 2015-07-25 09:07 UTC
I have installed this package and it some files that did not show previews now do.

Unfortunately it is not all of them. That is, some still refuse to show their thumbnail instead of their filetype icon.

How can I go about debugging this? Here is what I found in the console:

```
25/07/15 11:00:28,905 QuickLookUIHelper[15512]: NSFileSandboxingRequestRelatedItemExtension: an error was received from pboxd instead of a token. Domain: NSPOSIXErrorDomain, code: 1
25/07/15 11:00:28,906 QuickLookUIHelper[15512]: +[NSFileCoordinator addFilePresenter:] could not get a sandbox extension. primaryPresentedItemURL: file:///Users/username/directory/filename-1.mp4, presentedItemURL: file:///Users/username/directory/filename-1.AAE
25/07/15 11:00:31,443 QuickLookUIHelper[15512]: NSFileSandboxingRequestRelatedItemExtension: an error was received from pboxd instead of a token. Domain: NSPOSIXErrorDomain, code: 1
25/07/15 11:00:31,443 QuickLookUIHelper[15512]: +[NSFileCoordinator addFilePresenter:] could not get a sandbox extension. primaryPresentedItemURL: file:///Users/username/directory/filename-2.mp4, presentedItemURL: file:///Users/username/directory/filename-2.AAE
25/07/15 11:00:34,039 QuickLookUIHelper[15512]: NSFileSandboxingRequestRelatedItemExtension: an error was received from pboxd instead of a token. Domain: NSPOSIXErrorDomain, code: 1
25/07/15 11:00:34,039 QuickLookUIHelper[15512]: +[NSFileCoordinator addFilePresenter:] could not get a sandbox extension. primaryPresentedItemURL: file:///Users/username/directory/filename-3.mp4, presentedItemURL: file:///Users/username/directory/filename-3.AAE
```

Both QuickTime and the quicklook player *can* play the files. They are made the same exact way as the ones whose thumbnails show.

Judging from the error messages it seems like the problem is related to sandboxing. No idea where to go from there tho. Are there permissions that need to be set/changed? Both sets of files (w/ and w/o thumbnails) are in the same directory and have the same permissions.

Thank you!

**Comment by Marginal** [comment] 2015-07-25 13:26
QuickLook is looking for [AAE "sidecar"](http://fileformats.archiveteam.org/wiki/AAE_sidecar_format) files for each of these MP4 files, and getting a sandbox error (NSPOSIXErrorDomain code:1 is "Operation not permitted").

I'm not able to reproduce this problem. From Googling it looks like some other people get this error with JPEG files, but I haven't found a suggested solution. So a whole lot of questions:

- What version of OSX are you using?
- Where do these MP4 files come from? - i.e. did you use the "Image Capture" app to copy them from a camera, or did you copy them from a camera's SD card directly?
- Have you viewed and/or modified these files in the Photos app?
- Does the file /Users/username/directory/filename-1.AAE exist? Or did it used to exist and you deleted it?
- Please type `xattr /Users/username/directory/filename-1.mp4 /Users/username/directory/filename-1.AAE` in the Terminal app.

Please re-generate thumbnails by typing `qlmanage -r cache` in Terminal, and re-launching Finder.

- Do the same set of files fail to show a thumbnail, or a different set of files? (i.e. is the problem reproducible or intermittent)?
- Do these NSFileSandboxingRequestRelatedItemExtension errors in the console appear while the thumbnails are being generated, or when you try to preview the problematic files, or both?

**Comment by ear** [comment] 2015-07-25 13:41
Thank you for the quick reply. Here's a whole lot of answers.

* Yosemite 10.10.3
* The MP4 are remuxed FLVs (copying the native H.264 and AAC streams w/ ffmpeg, no transcoding.) I have a sizeable collection of those and it's only a fraction that displays the problem.
* Photos never touched those files. (I actually have never let the Photos up even run once.)
* The AAE files do not exist, as far as I can tell.
* `xattr` showed `com.apple.quarantine` for filename-1.mp4 but not for for the others. I believe it was coincidental and unrelated. (Removing the attribute does not change anything.)

I have regenerated the thumbnails with `qlmanage -r cache` and relaunched the Finder.

* The same set of files do fail to show a thumbnail. The same set of files that did show a thumbnail also still does. The problem appears to be reproducible.
* The errors appear in the console when I try to preview problematic files. (I assume by "while thumbnails are being generated" you mean during the execution of `qlmanage`.) I can trigger it consistently by pressing either `SPC` and activating Quick Look, or `⌘+i` and looking at the Preview pane of the info window. In the latter case the spinner starts spinning, then the error pops up in the console, and the spinner disappears. No preview is shown in there.

Hope it helps!

**Comment by Marginal** [comment] 2015-07-25 13:44
Thanks, that's very helpful. 

By "while thumbnails are being generated" I mean when you re-launch Finder and it starts filling in the thumbnails.

Some more questions:
Please delete QLVideo's quicklook generator with `sudo rm -rf /Library/QuickLook/Video.qlgenerator`, re-generate thumbnails with `qlmanage -r cache`, and re-launch Finder.

- Do the same set of files fail to show a thumbnail? (i.e. is the problem with QLVideo or with QuickLook itself)?
- Do these NSFileSandboxingRequestRelatedItemExtension errors in the console appear while the thumbnails are being generated, or when you try to preview the problematic files, or both, or neither?

**Comment by ear** [comment] 2015-07-25 13:51
Wow.

When I did `qlmanage -r cache` before, the same set of files would get and not get a thumbnail. Now that I deleted the QLVideo's quicklook generator a _different_ set of files both do and don't get a thumbnail. In particular: 4 out of 6 that did not before, now do; and 2 out of 20 that before did, now don't.

I am very confused.

**Comment by ear** [comment] 2015-07-25 13:54
Sorry I forgot to answer the second question: the errors only appear when I do the two things I described before. That is either `SPC` or `⌘+i` on files.

For some reason it hadn't occur to me to try those commands on files w/ thumbnails. I can confirm that the error appears on _all_ files. I had only tried it on thumbnail-less files before.

**Comment by Marginal** [comment] 2015-07-25 16:00
Having investigated further I think that the NSFileSandboxingRequestRelatedItemExtension messages in the console are a red-herring - I can get these messages when previewing otherwise fine .mp4 and other "native" file files.

When QLVideo is installed it handles thumbnails for all types of video (but lets QuickLookUI display previews for "native" file types that it thinks it understands). This might explain the difference in the thumbnails that you see with QLVideo installed and not installed.

So I think the problem may be with your .mp4 files. I wouldn't be surprised if the MPEG4 streams in the original FLV files were badly encoded. Do you still have the original FLV files? When QLVideo is installed and Finder re-started is there any correlation between the problematic MP4 file thumbnails and the FLV file thumbnails?

**Comment by ear** [comment] 2015-07-26 08:20
I think you are right. The provider of those video streams is not very good at making them perfect, that is for sure. I have received warnings from ffmpeg many a time during remuxing.

The set of files that get a thumbnail mostly swap when using the default quick look provider versus QLVideo. What is good is that QLVideo gets the most right. Do you think we could make it even more "accepting" in its workings? How could we debug what is going on with the few that it is missing?

Again I feel like that if QuickTime can play a video, then we should be able to get a thumbnail for it. Maybe a bit of logic that tries to seek into a random place a second time if the first try does not succeed? I look forward trying to make this work :star2:

**Comment by Marginal** [comment] 2015-07-26 11:26
> Do you think we could make it even more "accepting" in its workings? How could we debug what is going on with the few that it is missing?

I'm using the ffmpeg library and it doesn't really have any tolerance settings. But it might be possible to work around the problem I know where ffmpeg is failing. Could you make one of these problematic videos available on Dropbox for testing or upload it to my ftp site if I email you the details?

> Again I feel like that if QuickTime can play a video, then we should be able to get a thumbnail for it. Maybe a bit of logic that tries to seek into a random place a second time if the first try does not succeed?

I'm surprised that QuickTime Player 10 can play the videos but QuickLook Preview can't since they both use the same AVFoundation framework when playing "native" files.

Seek is the thing that's most likely to go wrong with poorly encoded files in my experience. QLVideo tries to seek to half-way through the video, and if that fails tries to use the first frame for the thumbnail.

**Comment by Marginal** [comment] 2015-08-03 13:43
Closing this since cannot reproduce the problem without sample files.

**Closed by Marginal** 2015-08-03 13:43 UTC
